### ISSUE TITLE
Allow only 1 vote

### ISSUE THREAD

**Issue by alefelc** [Dric/simple-photos-contest#2]
Hi, first at all. Awesome system.

I need to make the system only supports one single vote, not for every photo, but in general. 

That is, a person may cast only one vote to image he likes.

The system currently allows one vote for each photo.

How can I do that?

Thanks!

**Comment by Dric** [comment]
I will look at that, thanks for using it !

**Comment by Dric** [comment]
Done in v1.2.

To upgrade version, do not forget to run this sql command : 

    ALTER TABLE `contests` ADD `voting_type` VARCHAR( 10 ) NOT NULL DEFAULT "open" ;

**Comment by alefelc** [comment]
Thanks man.

I found a new issue: The contest don't activate it in admin panel when I click the plus button.

**Comment by Dric** [comment]
Please open a new issue, as this is another problem.
